<a target="_blank" href="https://colab.research.google.com/github/phitter-hub/phitter-kernel/blob/main/examples/fit_continuous_iris.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import os
import sys

import pandas

In [11]:
if os.getenv("COLAB_RELEASE_TAG"):
   !pip install phitter --quiet
else:
   sys.path.append("../../")

In [12]:
import phitter

In [13]:
df = pandas.read_csv("https://gist.githubusercontent.com/phitter-hub/6e1cdb92a5f518c7459484c619185fc5/raw/4072c5233d03204d8999943398b23c2393bcd637/iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
data = df["SepalWidthCm"].to_numpy()

In [15]:
phi = phitter.Phitter(data=data)
phi.fit(n_workers=2)

In [16]:
phi.best_distribution

{'id': 'gamma',
 'parameters': {'alpha': 49.61019269899973, 'beta': 0.061559930204858414}}

In [17]:
phi.df_sorted_distributions

        distribution passed            aic            bic  \

0              gamma      ✅     175.466913     181.488184
1          lognormal      ✅     175.758136     181.779406
2   inverse_gaussian      ✅     175.801256     181.822527
3             erlang      ✅     175.917795     181.939065
4           nakagami      ✅     176.298530     182.319801
..               ...    ...            ...            ...
58    error_function     ✖️    7617.516680    7620.527316
59     inverse_gamma     ✖️   11190.673576   11196.694846
60                 f     ✖️   16954.378780   16960.400051
61            gibrat     ✖️   33654.804005   33660.825276
62          loggamma     ✖️  157502.820361  157511.852267

                                  parameters     chi_square                 \
                                             test_statistic critical_value
0                alpha: 49.61, beta: 0.06156   9.338464e+00      15.507313
1                   mu: 1.106, sigma: 0.1413   1.018456e+01      15.507313
2                   mu: 3.054, lambda: 151.5   1.029467e+01      15.507313
3                       k: 50, beta: 0.06156   9.426407e+00      15.507313
4                     m: 12.28, omega: 9.514   9.462231e+00      15.507313
..                                       ...            ...            ...
58                                  h: 1.631            NaN            NaN
59                 alpha: 163.2, beta: 889.3   1.791086e+40      15.507313
60                    df1: 474.5, df2: 352.4            NaN            NaN
61                 loc: 2.723, scale: 0.2006            NaN            NaN
62  c: 8.51e+04, mu: 4.492e-05, sigma: 0.269            NaN            NaN

                      kolmogorov_smirnov                               \
     p_value rejected     test_statistic critical_value       p_value
0   0.314553    False           0.084365       0.109714  2.231328e-01
1   0.252310    False           0.075523       0.109714  3.419896e-01
2   0.244950    False           0.075375       0.109714  3.442974e-01
3   0.307611    False           0.106416       0.109714  6.210810e-02
4   0.304814    False           0.091959       0.109714  1.485840e-01
..       ...      ...                ...            ...           ...
58       NaN     None           0.999998       0.109714  0.000000e+00
59  0.000000     True           0.997892       0.109714  0.000000e+00
60       NaN     None           1.000000       0.109714  0.000000e+00
61       NaN     None           0.220000       0.109714  7.380515e-07
62       NaN     None           0.553333       0.109714  0.000000e+00

            anderson_darling
   rejected   test_statistic critical_value   p_value rejected
0     False         0.779201        2.49359  0.496056    False
1     False         0.793142        2.49359  0.485791    False
2     False         0.799207        2.49359  0.481392    False
3     False         1.018681        2.49359  0.347492    False
4     False         0.854976        2.49359  0.442826    False
..      ...              ...            ...       ...      ...
58     True              NaN            NaN       NaN     None
59     True      4381.024485        2.49359  0.000004     True
60     True      5305.062015        2.49359  0.000004     True
61     True              NaN            NaN       NaN     None
62     True              NaN            NaN       NaN     None

[63 rows x 17 columns]

In [18]:
phi.plot_histogram()

In [19]:
phi.plot_histogram_distributions()

In [20]:
phi.plot_distribution("burr_4p")

In [21]:
phi.plot_ecdf()

In [22]:
phi.plot_ecdf_distribution("logistic")

In [23]:
phi.qq_plot("logistic")

In [24]:
phi.qq_plot_regression("logistic")